import pathlib

target = pathlib.Path(__file__).parent / "_aria_cases_batch_B.py"

code = []
code.append(chr(34)*3)
code.append("ARIA Investigation Batch B: 5 vendors investigated.")
code.append("Dispositions: 1 confirmed_corrupt, 1 false_positive, 3 needs_review.")
code.append("Run: cd backend && python scripts/_aria_cases_batch_B.py")
code.append(chr(34)*3)
code.append("import sys")
code.append("sys.stdout.reconfigure(encoding='utf-8')")
code.append("import sqlite3, json")
code.append("from pathlib import Path")
code.append("")
code.append("DB = Path(__file__).parent.parent / 'RUBLI_NORMALIZED.db'")
code.append("DATA = Path(__file__).parent / '_batch_B_aria_data.json'")
code.append("")
code.append("conn = sqlite3.connect(str(DB))")
code.append("conn.execute('PRAGMA journal_mode=WAL')")
code.append("conn.execute('PRAGMA busy_timeout=60000')")
code.append("")
code.append("with open(DATA, 'r', encoding='utf-8') as f:")
code.append("    payload = json.load(f)")
code.append("")
code.append("gt_cases = payload['gt_cases']")
code.append("aria_updates = payload['aria_updates']")
code.append("")
code.append("# Get next case ID")
code.append("row = conn.execute('SELECT MAX(id) FROM ground_truth_cases').fetchone()")
code.append("next_id = (row[0] or 0) + 1")
code.append("print(f'Starting from case ID {next_id}')")
code.append("")
code.append("# Insert GT cases")
code.append("for i, c in enumerate(gt_cases):")
code.append("    cid = f'CASE-{next_id + i:04d}'")
code.append("    c['cid'] = cid")
code.append("    conn.execute(")
code.append("        'INSERT OR REPLACE INTO ground_truth_cases '")
code.append("        '(id, case_id, case_name, case_type, confidence_level, sector, notes, estimated_fraud_mxn, year_start, year_end) '")
code.append("        'VALUES (?,?,?,?,?,?,?,?,?,?)',")
code.append("        (next_id + i, cid, c['name'], c['type'], c['conf'], c['sector'],")
code.append("         c['notes'], c['fraud'], c['ys'], c['ye']))")
code.append("    vid = c['vid']")
code.append("    nm = c['name']")
code.append("    print(f'  Inserted GT case {cid}: {nm}')")
code.append("")
code.append("# Insert GT vendors")
code.append("for c in gt_cases:")
code.append("    conn.execute(")
code.append("        'INSERT OR IGNORE INTO ground_truth_vendors '")
code.append("        '(case_id, vendor_id, vendor_name_source, evidence_strength, match_method) '")
code.append("        'VALUES (?,?,?,?,?)',")
code.append("        (c['cid'], c['vid'], c['vname'], c['ev'], 'aria_investigation'))")
code.append("    vid = c['vid']")
code.append("    print(f'  Inserted GT vendor v={vid}')")
code.append("")
code.append("# Tag contracts for GT cases")
code.append("tagged = 0")
code.append("for c in gt_cases:")
code.append("    rows = conn.execute('SELECT id FROM contracts WHERE vendor_id = ?', (c['vid'],)).fetchall()")
code.append("    for row in rows:")
code.append("        conn.execute(")
code.append("            'INSERT OR IGNORE INTO ground_truth_contracts (case_id, contract_id) VALUES (?, ?)',")
code.append("            (c['cid'], row[0]))")
code.append("        tagged += 1")
code.append("print(f'  Tagged {tagged} contracts')")
code.append("")
code.append("# Update ARIA queue for GT cases")
code.append("for c in gt_cases:")
code.append("    conn.execute(")
code.append("        'UPDATE aria_queue SET in_ground_truth=1, review_status=?, memo_text=? WHERE vendor_id=?',")
code.append("        (c['disposition'], c.get('memo', ''), c['vid']))")
code.append("    vid = c['vid']")
code.append("    disp = c['disposition']")
code.append("    print(f'  ARIA v={vid}: {disp}')")
code.append("")
code.append("# Update ARIA queue for non-GT vendors")
code.append("for u in aria_updates:")
code.append("    conn.execute(")
code.append("        'UPDATE aria_queue SET review_status=?, memo_text=? WHERE vendor_id=?',")
code.append("        (u['disposition'], u.get('memo', ''), u['vid']))")
code.append("    vid = u['vid']")
code.append("    disp = u['disposition']")
code.append("    if u.get('fp_patent_exception'):")
code.append("        conn.execute('UPDATE aria_queue SET fp_patent_exception=1 WHERE vendor_id=?', (vid,))")
code.append("        print(f'  ARIA v={vid}: {disp} + fp_patent_exception')")
code.append("    elif u.get('new_vendor_risk_fix') is not None:")
code.append("        nv = u['new_vendor_risk_fix']")
code.append("        conn.execute('UPDATE aria_queue SET new_vendor_risk=? WHERE vendor_id=?', (nv, vid))")
code.append("        print(f'  ARIA v={vid}: {disp} + new_vendor_risk={nv}')")
code.append("    else:")
code.append("        print(f'  ARIA v={vid}: {disp}')")
code.append("")
code.append("conn.commit()")
code.append("print('Committed.')")
code.append("")
code.append("# Verify")
code.append("print('--- VERIFICATION ---')")
code.append("for vid in [277243, 313628, 294526, 259101, 239570]:")
code.append("    r = conn.execute(")
code.append("        'SELECT vendor_id, review_status, fp_patent_exception, in_ground_truth, new_vendor_risk '")
code.append("        'FROM aria_queue WHERE vendor_id=?', (vid,)).fetchone()")
code.append("    if r:")
code.append("        print(f'  v={r[0]}: status={r[1]}, fp_patent={r[2]}, gt={r[3]}, new_v={r[4]}')")
code.append("")
code.append("r = conn.execute('SELECT COUNT(*) FROM ground_truth_cases').fetchone()")
code.append("print(f'Total GT cases: {r[0]}')")
code.append("r = conn.execute('SELECT COUNT(*) FROM ground_truth_vendors').fetchone()")
code.append("print(f'Total GT vendors: {r[0]}')")
code.append("")
code.append("conn.close()")
code.append("print('Done.')")

target.write_text(chr(10).join(code), encoding='utf-8')
print(f'Generated {target}')
