"""
Batch N: Write investigation memos for 18 GT cases.
Run AFTER _insert_cases_batch_N.py.
"""
import sys
sys.stdout.reconfigure(encoding="utf-8")
import sqlite3
import json
from pathlib import Path
from datetime import datetime

DB = Path(__file__).parent.parent / "RUBLI_NORMALIZED.db"
DATA = Path(__file__).parent / "_batch_N_data.json"

conn = sqlite3.connect(str(DB))
conn.execute("PRAGMA journal_mode=WAL")
conn.execute("PRAGMA busy_timeout=60000")

with open(DATA, "r", encoding="utf-8") as f:
    cases_data = json.load(f)

MEMO_TEMPLATE = """## Investigation Memo: {name}

**Case ID**: {cid}
**Vendor ID**: {vid}
**Case Type**: {case_type}
**Confidence**: {conf}
**Sector**: {sector}
**Estimated Value**: {fraud_fmt}
**Period**: {ys}-{ye}

### Summary
{notes}

### Red Flags
{red_flags}

### Recommendation
This vendor has been flagged for investigation based on procurement pattern analysis.
Risk indicators are statistical signals, not proof of wrongdoing.

---
*Generated by ARIA Batch N pipeline on {timestamp}*
"""

RED_FLAGS_MAP = {
    "ghost_company": "- New/unknown vendor with large direct award contracts\n- Limited operational history\n- Single institution dependency\n- Potential shell company indicators",
    "institution_capture": "- Disproportionate concentration at single institution\n- High direct award rate bypassing competitive procedures\n- Rapid value growth suggesting preferential treatment\n- Pattern consistent with institutional capture",
    "monopoly": "- Dominant market position at specific institution\n- High single-bid rate indicating suppressed competition\n- Large contract values relative to vendor profile\n- Consistent award pattern over multiple years",
    "industry_mismatch": "- Company name/sector does not match contract category\n- Vendor operating outside apparent area of expertise\n- Possible front company or misclassified entity\n- Requires verification of actual business operations",
    "overpricing": "- Contract values significantly above sector norms\n- Rapid value escalation in short time period\n- New entity receiving billion-peso contracts\n- Limited competitive pressure on pricing",
}

now = datetime.now().strftime("%Y-%m-%d %H:%M")
written = 0
for c in cases_data:
    fraud_b = c["fraud"] / 1e9
    fraud_fmt = f"${fraud_b:.2f}B MXN" if fraud_b >= 1 else f"${c['fraud']/1e6:.0f}M MXN"
    red_flags = RED_FLAGS_MAP.get(c["type"], "- Multiple risk indicators detected")
    
    memo = MEMO_TEMPLATE.format(
        name=c["name"],
        cid=c["cid"],
        vid=c["vid"],
        case_type=c["type"],
        conf=c["conf"],
        sector=c["sector"],
        fraud_fmt=fraud_fmt,
        ys=c["ys"],
        ye=c["ye"],
        notes=c["notes"],
        red_flags=red_flags,
        timestamp=now,
    )
    
    conn.execute(
        """INSERT OR REPLACE INTO aria_memos (case_id, vendor_id, memo_text, created_at)
        VALUES (?, ?, ?, ?)""",
        (c["cid"], c["vid"], memo.strip(), now)
    )
    
    # Also update aria_queue memo fields
    conn.execute(
        """UPDATE aria_queue SET memo_text=?, memo_generated_at=? WHERE vendor_id=?""",
        (memo.strip(), now, c["vid"])
    )
    written += 1

conn.commit()
conn.close()
print(f"Batch N: Wrote {written} memos")
